name: build and Inspect React App

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout the App
        uses: actions/checkout@v2
      
      - name: hello Wolrd
        run: echo "Hello World"
        
      - name: install dependencies
        run: npm i
      
      - name: build App
        run: npm run build

      - name : debug build
        run: ls -la 